# version: "3.8"

networks:
  es-net:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    networks:
      - es-net
    ports:
      [9200:9200]
    environment:
      xpack.security.enabled: false
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    networks:
      - es-net
    ports:
      [5601:5601]
    environment:
      ELASTICSEARCH_HOSTS: http://es-container:9200